import React, { PropsWithChildren } from "react";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = (props: PropsWithChildren) => {
  return (
    <html lang="en" className={inter.className}>
      <body>{props.children}</body>
    </html>
  );
};

export default RootLayout;
